require("basic")
require("keybindings")
require("colorscheme")
require("plugins")
require("config.notify")
require("config.autopairs")
require("config.nvim-tree")
require("config.bufferline")
require("config.lualine")
require("config.telescope")
require("config.alpha")
require("config.project")
require("config.nvim-treesitter")

require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("lsp.null-ls")
