-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

local map = vim.keymap.set

map("n", "<C-j>", "6j", { noremap = true, silent = true })
map("n", "<C-k>", "6k", { noremap = true, silent = true })
--
-- DAP基础调试操作
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Debug: Toggle Breakpoint" })
map("n", "<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Debug: Set Conditional Breakpoint" })
map("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "Debug: Start/Continue" })
map("n", "<leader>dC", function()
  require("dap").run_to_cursor()
end, { desc = "Debug: Run to Cursor" })
map("n", "<leader>dg", function()
  require("dap").goto_()
end, { desc = "Debug: Go to line (no execute)" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "Debug: Step Into" })
map("n", "<leader>dj", function()
  require("dap").down()
end, { desc = "Debug: Down" })
map("n", "<leader>dk", function()
  require("dap").up()
end, { desc = "Debug: Up" })
map("n", "<leader>dl", function()
  require("dap").run_last()
end, { desc = "Debug: Run Last" })
map("n", "<leader>do", function()
  require("dap").step_over()
end, { desc = "Debug: Step Over" })
map("n", "<leader>dO", function()
  require("dap").step_out()
end, { desc = "Debug: Step Out" })
map("n", "<leader>dp", function()
  require("dap").pause()
end, { desc = "Debug: Pause" })
map("n", "<leader>dr", function()
  require("dap").repl.toggle()
end, { desc = "Debug: Toggle REPL" })
map("n", "<leader>ds", function()
  require("dap").session()
end, { desc = "Debug: Session" })
map("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "Debug: Terminate" })

-- DAP UI 操作
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Debug: Toggle UI" })
map("n", "<leader>dw", function()
  require("dapui").toggle({ reset = true })
end, { desc = "Debug: Reset UI" })

-- 浮动窗口
map("n", "<leader>df", function()
  local widgets = require("dap.ui.widgets")
  widgets.centered_float(widgets.frames)
end, { desc = "Debug: Frames" })
map("n", "<leader>dS", function()
  local widgets = require("dap.ui.widgets")
  widgets.centered_float(widgets.scopes)
end, { desc = "Debug: Scopes" })

-- Visual mode 操作
map("v", "<leader>dh", function()
  require("dap.ui.widgets").hover()
end, { desc = "Debug: Hover" })
map("v", "<leader>dp", function()
  require("dap.ui.widgets").preview()
end, { desc = "Debug: Preview" })
